### ISSUE TITLE
Win Binaries

### ISSUE THREAD

**Issue by martin-lueders** [martin-lueders/Befaco#1]
[Befaco-1.0.0-win.zip](https://github.com/martin-lueders/Befaco/files/3316092/Befaco-1.0.0-win.zip)

**Comment by vcvrackideas** [comment]
thanks! slew limiter linear responce in the poly mode turns the bipolar signal out of range, please look at this patch
[win build issue.zip](https://github.com/martin-lueders/Befaco/files/3316572/win.build.issue.zip)

**Comment by martin-lueders** [comment]
Confirmed. I just fixed it and will upload a new distribution in a while.
